// <auto-generated />
using System;
using Mc2.CrudTest.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mc2.CrudTest.Persistence.Migrations
{
    [DbContext(typeof(CustomerDbContext))]
    [Migration("20220611224418_DB Initialize")]
    partial class DBInitialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Mc2.CrudTest.Domain.Models.Entities.CustomerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BankAccountNumber")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("PhoneNumber")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("Email", "FirstName", "LastName", "DateOfBirth")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BankAccountNumber = "6037-9917-0000-0000",
                            DateOfBirth = new DateTime(2022, 3, 15, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "taherfatta11@gmail.com",
                            FirstName = "taher 1",
                            LastName = "fattahi 1",
                            PhoneNumber = 989115467885m
                        },
                        new
                        {
                            Id = 2,
                            BankAccountNumber = "6037-9917-0000-0000",
                            DateOfBirth = new DateTime(2022, 9, 16, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "taherfatta111@gmail.com",
                            FirstName = "taher 2",
                            LastName = "fattahi 2",
                            PhoneNumber = 989115467886m
                        },
                        new
                        {
                            Id = 3,
                            BankAccountNumber = "6037-9917-0000-0000",
                            DateOfBirth = new DateTime(2022, 8, 17, 6, 0, 1, 0, DateTimeKind.Unspecified),
                            Email = "taherfatta1111@gmail.com",
                            FirstName = "taher 3",
                            LastName = "fattahi 3",
                            PhoneNumber = 989115467887m
                        },
                        new
                        {
                            Id = 4,
                            BankAccountNumber = "6037-9917-0000-0000",
                            DateOfBirth = new DateTime(2022, 1, 18, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "taherfatta11111@gmail.com",
                            FirstName = "taher 4",
                            LastName = "fattahi 4",
                            PhoneNumber = 989115467888m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
